server:
  port: 3000
  tomcat:
    uri-encoding: utf-8
spring:
  datasource:
    host: localhost
    port: 3306
    dbname: yangchen
    url: jdbc:mysql://${spring.datasource.host}:${spring.datasource.port}/${spring.datasource.dbname}?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true&serverTimezone=UTC
    username: root
    password: 123456
  mvc:
    static-path-pattern: /static/**
    view:
      prefix: classpath:/templates/
      suffix: .html
  thymeleaf:
    cache: false

mybatis-plus:
  check-config-location: false
  mapper-locations: classpath:mapper/*.xml

excel:
  path: src/main/resources/excel
