server:
  port: 3000

spring:
  datasource:
    host: localhost
    port: 3306
    dbname: yangchen
    url: jdbc:mysql://${spring.datasource.host}:${spring.datasource.port}/${spring.datasource.dbname}?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true&serverTimezone=UTC
    username: root
    password: 123456
  devtoolsrestart.enabled: true

mybatis-plus:
  check-config-location: false


